title: Canon IJ Network Device Setup Utility
description: Go to ij.start.canon and enter the Canon printer model number and get the software downloaded to your device.Set up your iJ Canon printer using the USB cable and following the steps outlined here.
